### ISSUE TITLE
Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by philpott** [illow-io/illow-CMP-template-GTM#1]
https://github.com/illow-io/illow-CMP-template-GTM/blob/047a5bb23fb05fb4be803bebf7444763e818b6fa/template.tpl#L76C3-L76C19

When reviewing your template we've noticed that the setDefaultConsentState call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

**Comment by danielfx90** [comment]
@philpott solved!

https://github.com/illow-io/illow-CMP-template-GTM/blob/084f647b8d7e3cf7a653461214aa211c69f07373/template.tpl#L77
